import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Zap, MessageSquare, MapPin, ChevronRight, Dumbbell, Brain, TrendingUp } from 'lucide-react';
import Button from '../components/Button';

const FEATURES = [
  {
    icon: Brain,
    title: 'AI-Powered Plans',
    desc: 'Personalised workout and nutrition plans generated by AI, tailored to your body and goals.',
    color: 'green',
  },
  {
    icon: MessageSquare,
    title: 'Fitness Chatbot',
    desc: 'Ask anything about fitness, nutrition, or recovery and get instant expert-level answers.',
    color: 'blue',
  },
  {
    icon: MapPin,
    title: 'Locate Nearby Gyms',
    desc: 'Find gyms, parks, and fitness centres nearby using interactive maps.',
    color: 'purple',
  },
  {
    icon: TrendingUp,
    title: 'Track Progress',
    desc: 'Monitor your streak, calories, and long-term fitness journey with visual dashboards.',
    color: 'orange',
  },
];

const ICON_COLORS = {
  green:  'bg-green-100 text-green-600 dark:bg-green-900/40 dark:text-green-400',
  blue:   'bg-blue-100 text-blue-600 dark:bg-blue-900/40 dark:text-blue-400',
  purple: 'bg-purple-100 text-purple-600 dark:bg-purple-900/40 dark:text-purple-400',
  orange: 'bg-orange-100 text-orange-600 dark:bg-orange-900/40 dark:text-orange-400',
};

const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.12 } },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } },
};

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-green-50 dark:from-gray-950 dark:via-gray-900 dark:to-gray-950">
      {/* ── Hero ──────────────────────────────────────────────── */}
      <section className="relative overflow-hidden">
        {/* Background blobs */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <div className="absolute -top-40 -right-40 w-96 h-96 bg-green-200/30 dark:bg-green-900/20 rounded-full blur-3xl" />
          <div className="absolute -bottom-20 -left-20 w-80 h-80 bg-emerald-200/20 dark:bg-emerald-900/10 rounded-full blur-3xl" />
        </div>

        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-20 relative">
          <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="flex flex-col items-center text-center gap-8 max-w-3xl mx-auto"
          >
            {/* Badge */}
            <motion.div variants={itemVariants}>
              <span className="inline-flex items-center gap-2 px-4 py-1.5 bg-green-100 dark:bg-green-900/40 text-green-700 dark:text-green-400 text-sm font-medium rounded-full">
                <Zap className="w-3.5 h-3.5" />
                AI-Powered Fitness Ecosystem
              </span>
            </motion.div>

            {/* Headline */}
            <motion.h1
              variants={itemVariants}
              className="text-5xl sm:text-6xl lg:text-7xl font-bold tracking-tight text-gray-900 dark:text-gray-100 leading-[1.1]"
            >
              Your Personal{' '}
              <span className="bg-gradient-to-r from-green-500 to-emerald-600 bg-clip-text text-transparent">
                AI Fitness
              </span>{' '}
              Coach
            </motion.h1>

            {/* Sub */}
            <motion.p
              variants={itemVariants}
              className="text-lg sm:text-xl text-gray-500 dark:text-gray-400 max-w-2xl leading-relaxed"
            >
              FitAI generates personalised workout &amp; nutrition plans, answers your fitness
              questions in real-time, and helps you locate gyms nearby — all powered by AI.
            </motion.p>

            {/* CTAs */}
            <motion.div variants={itemVariants} className="flex flex-wrap gap-4 justify-center">
              <Link to="/generate">
                <Button size="lg" leftIcon={Zap}>
                  Generate My Plan
                </Button>
              </Link>
              <Link to="/chat">
                <Button size="lg" variant="secondary" leftIcon={MessageSquare}>
                  Chat with AI
                </Button>
              </Link>
            </motion.div>

            {/* Stats row */}
            <motion.div
              variants={itemVariants}
              className="flex flex-wrap justify-center gap-8 mt-4 text-center"
            >
              {[['10K+', 'Plans Generated'], ['98%', 'User Satisfaction'], ['24/7', 'AI Support']].map(
                ([val, lbl]) => (
                  <div key={lbl}>
                    <div className="text-2xl font-bold text-gray-900 dark:text-gray-100">{val}</div>
                    <div className="text-xs text-gray-500 mt-0.5">{lbl}</div>
                  </div>
                )
              )}
            </motion.div>
          </motion.div>
        </div>
      </section>

      {/* ── Features ──────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <h2 className="text-3xl font-bold text-gray-900 dark:text-gray-100 mb-3">
            Everything you need to get fit
          </h2>
          <p className="text-gray-500 dark:text-gray-400">
            One platform, all the tools to crush your fitness goals.
          </p>
        </motion.div>

        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.2 }}
          className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6"
        >
          {FEATURES.map(({ icon: Icon, title, desc, color }) => (
            <motion.div
              key={title}
              variants={itemVariants}
              className="bg-white dark:bg-gray-900 rounded-2xl p-6 border border-gray-100 dark:border-gray-800 shadow-sm hover:shadow-md transition-shadow group"
            >
              <div className={`w-11 h-11 rounded-xl flex items-center justify-center mb-4 ${ICON_COLORS[color]}`}>
                <Icon className="w-5 h-5" />
              </div>
              <h3 className="font-semibold text-gray-900 dark:text-gray-100 mb-2">{title}</h3>
              <p className="text-sm text-gray-500 dark:text-gray-400 leading-relaxed">{desc}</p>
            </motion.div>
          ))}
        </motion.div>
      </section>

      {/* ── CTA Banner ────────────────────────────────────────── */}
      <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pb-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="relative overflow-hidden bg-gradient-to-r from-green-500 to-emerald-600 rounded-3xl p-10 sm:p-16 text-white text-center shadow-xl"
        >
          <div className="absolute inset-0 overflow-hidden">
            <div className="absolute -top-10 -right-10 w-64 h-64 bg-white/10 rounded-full blur-2xl" />
            <div className="absolute -bottom-10 -left-10 w-64 h-64 bg-white/5 rounded-full blur-2xl" />
          </div>
          <div className="relative">
            <Dumbbell className="w-12 h-12 mx-auto mb-4 opacity-90" />
            <h2 className="text-3xl sm:text-4xl font-bold mb-3">Ready to transform?</h2>
            <p className="text-white/80 text-lg mb-8 max-w-lg mx-auto">
              Generate your first AI-powered fitness plan in under 60 seconds — completely free.
            </p>
            <Link to="/generate">
              <Button
                size="lg"
                className="bg-white text-green-600 hover:bg-gray-50 shadow-lg"
                rightIcon={ChevronRight}
              >
                Get Started Free
              </Button>
            </Link>
          </div>
        </motion.div>
      </section>
    </div>
  );
}
